# Generated by Django 5.2.11 on 2026-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_blood_bank', models.BooleanField(default=False)),
                ('category', models.CharField(default='Hospital', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
