# Generated by Django 5.2.11 on 2026-02-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroroute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
