# Generated by Django 5.2.7 on 2026-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aeroroute', '0002_location_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoFlyZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_lat', models.FloatField()),
                ('center_lon', models.FloatField()),
                ('radius_km', models.FloatField(default=0.5)),
                ('min_lat', models.FloatField(blank=True, null=True)),
                ('max_lat', models.FloatField(blank=True, null=True)),
                ('min_lon', models.FloatField(blank=True, null=True)),
                ('max_lon', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
